### ISSUE TITLE
request for source code

### ISSUE THREAD

**Issue by poursistani** [dalibo/cornac#55]
hi
I have a project I want to use cornac package. It is so complete.I could not view the source of "cornac.models.knn.similarity.compute_similarity" .  May you help me.

It would be so appriciated if you could help me.

**Comment by bersace** [comment]
Hi @poursistani thanks for reaching !

cornac move to gitlab : https://gitlab.com/dalibo/cornac

I'll archive this repository to avoid mistake.

**Comment by bersace** [comment]
Are you searching for AI project https://github.com/PreferredAI/cornac/ ?

This project is called pgCornac on PyPI. It's related to PostgreSQL deployement.
